#!/bin/bash
# kodi-skinstring ID WERT  (Kodi muss gestoppt sein) - setzt Skin-String in settings.xml
F=/root/.var/app/tv.kodi.Kodi/data/userdata/addon_data/skin.arctic.zephyr.modern/settings.xml
ID=$(echo "$1" | tr 'A-Z' 'a-z')
python3 - "$F" "$ID" "$2" <<'PY'
import sys,re
f,i,v=sys.argv[1:]; s=open(f).read()
pat=rf'<setting id="{re.escape(i)}" type="string">[^<]*</setting>'
new=f'<setting id="{i}" type="string">{v}</setting>'
s=re.sub(pat,new,s) if re.search(pat,s) else s.replace('</settings>',f'    {new}\n</settings>')
open(f,'w').write(s)
PY
